export type Bureau = "Equifax" | "Experian" | "TransUnion";

export type NegativeItem = {
  id: string;
  creditor: string;
  accountType: string;
  status: string;
  balance: string;
  opened: string;
  bureaus: Bureau[];
  disputeGround: string;
  recommended: boolean;
};

export type DemoClient = {
  id: string;
  name: string;
  address: string;
  cityStateZip: string;
  reportDate: string;
  scores: { bureau: Bureau; score: number }[];
};

export const DEMO_CLIENT: DemoClient = {
  id: "cli_jordan",
  name: "Jordan Hale",
  address: "1842 Meridian Avenue",
  cityStateZip: "Austin, TX 78702",
  reportDate: "September 12, 2026",
  scores: [
    { bureau: "Equifax", score: 612 },
    { bureau: "Experian", score: 598 },
    { bureau: "TransUnion", score: 605 },
  ],
};

export const NEGATIVE_ITEMS: NegativeItem[] = [
  {
    id: "item_01",
    creditor: "Capital One",
    accountType: "Revolving credit card",
    status: "Charge-off · 120 days late",
    balance: "$2,841",
    opened: "03/2019",
    bureaus: ["Equifax", "Experian", "TransUnion"],
    disputeGround: "Incomplete account verification / Metro 2 inconsistency",
    recommended: true,
  },
  {
    id: "item_02",
    creditor: "Synchrony Bank",
    accountType: "Retail revolving",
    status: "Collection · Midland Credit",
    balance: "$1,204",
    opened: "11/2020",
    bureaus: ["Experian", "TransUnion"],
    disputeGround: "Not mine / lack of signed agreement documentation",
    recommended: true,
  },
  {
    id: "item_03",
    creditor: "OneMain Financial",
    accountType: "Installment loan",
    status: "Late 30 / Late 60",
    balance: "$4,670",
    opened: "07/2021",
    bureaus: ["Equifax", "TransUnion"],
    disputeGround: "Inaccurate late history vs. payment records",
    recommended: true,
  },
  {
    id: "item_04",
    creditor: "Medical Collection — Ascension",
    accountType: "Medical",
    status: "Open collection",
    balance: "$486",
    opened: "02/2023",
    bureaus: ["Equifax", "Experian"],
    disputeGround: "Unverified medical debt / billing dispute pending",
    recommended: false,
  },
  {
    id: "item_05",
    creditor: "Hard Inquiry — Affirm",
    accountType: "Inquiry",
    status: "Hard pull",
    balance: "—",
    opened: "08/2025",
    bureaus: ["Experian"],
    disputeGround: "Unauthorized inquiry / no permissible purpose shown",
    recommended: true,
  },
];

export function buildLetter(
  client: DemoClient,
  bureau: Bureau,
  items: NegativeItem[],
): string {
  const today = "September 17, 2026";
  const itemLines = items
    .filter((item) => item.bureaus.includes(bureau))
    .map(
      (item, index) =>
        `${index + 1}. ${item.creditor} — ${item.accountType}\n   Status reported: ${item.status}\n   Balance: ${item.balance} · Opened: ${item.opened}\n   Basis for dispute: ${item.disputeGround}`,
    )
    .join("\n\n");

  const bureauAddress =
    bureau === "Equifax"
      ? "Equifax Information Services LLC\nP.O. Box 740256\nAtlanta, GA 30374"
      : bureau === "Experian"
        ? "Experian\nP.O. Box 4500\nAllen, TX 75013"
        : "TransUnion LLC\nConsumer Dispute Center\nP.O. Box 2000\nChester, PA 19016";

  return `${client.name}
${client.address}
${client.cityStateZip}

${today}

${bureauAddress}

Re: Formal dispute under the Fair Credit Reporting Act (15 U.S.C. § 1681i)

To Whom It May Concern:

I am writing to dispute the following information in my credit file. I formally request that you conduct a reasonable reinvestigation of each item listed below and delete or correct any information that cannot be verified as accurate, complete, and timely.

Disputed items:

${itemLines || "No selected items report on this bureau for this demo packet."}

Please investigate these matters and provide written results of your reinvestigation, including a free updated copy of my consumer report if any changes are made.

Thank you for your prompt attention.

Sincerely,

${client.name}

— Generated by Fresh Start Demo · Not legal advice · Sample correspondence only —
`;
}
