import PDFDocument from "pdfkit";
import type { ClassifiedDisputeItem, ConsumerIdentity } from "@/lib/domain/types";

/** Generate a marked report-excerpt style enclosure for disputed items. */
export async function renderAnnotatedExcerptPdf(input: {
  consumer: ConsumerIdentity;
  items: ClassifiedDisputeItem[];
  reportDate?: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: 54, bottom: 54, left: 54, right: 54 },
      info: {
        Title: `Annotated credit report excerpt — ${input.consumer.fullName}`,
        Author: "Fresh Start",
      },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(11).fillColor("#0c2e2b").font("Times-Bold");
    doc.text("ANNOTATED CREDIT REPORT EXCERPT", { align: "left" });
    doc.moveDown(0.4);
    doc.font("Times-Roman").fontSize(9).fillColor("#5a6f6a");
    doc.text(
      "Enclosure for FCRA dispute — disputed items marked below. Generated by Fresh Start.",
    );
    doc.moveDown(0.8);

    doc.fontSize(10).fillColor("#0c2e2b");
    doc.text(`Consumer: ${input.consumer.fullName}`);
    doc.text(`Address: ${input.consumer.addressLine1}, ${input.consumer.cityStateZip}`);
    if (input.consumer.reportFileNumber) {
      doc.text(`Report / file #: ${input.consumer.reportFileNumber}`);
    }
    if (input.reportDate) doc.text(`Report date: ${input.reportDate}`);
    doc.moveDown(1);

    input.items.forEach((item, index) => {
      // Highlight bar
      const y = doc.y;
      doc.save();
      doc.rect(54, y, 504, 4).fill("#c45c26");
      doc.restore();
      doc.moveDown(0.6);

      doc.font("Times-Bold").fontSize(11).fillColor("#0c2e2b");
      doc.text(`DISPUTED ITEM ${index + 1} — ${item.creditor}`);
      doc.font("Times-Roman").fontSize(10);
      doc.text(`Type: ${item.accountType}`);
      doc.text(`Account (as shown): ${item.accountNumber ?? "[see full report]"}`);
      doc.text(`Status reported: ${item.statusReported}`);
      if (item.balance) doc.text(`Balance reported: ${item.balance}`);
      if (item.dateOpened) doc.text(`Opened: ${item.dateOpened}`);
      doc.text(`Bureaus: ${item.bureaus.join(", ")}`);
      doc.text(`Furnisher: ${item.furnisherName ?? item.creditor}`);
      doc.moveDown(0.3);
      doc.font("Times-Bold").text("Marked inaccuracy:");
      doc.font("Times-Roman").text(item.groundRationale, { width: 500 });
      doc.moveDown(0.8);

      if (doc.y > 680) doc.addPage();
    });

    doc.fontSize(8).fillColor("#5a6f6a");
    doc.text(
      "This excerpt is a working enclosure derived from the consumer’s report data for dispute identification. Keep originals; send copies only.",
    );

    doc.end();
  });
}
