import PDFDocument from "pdfkit";
import type { LetterPacket } from "@prisma/client";

export type PdfLetterInput = {
  recipientName: string;
  recipientType: string;
  bureau?: string | null;
  bodyText: string;
  trackingNumber?: string | null;
  mailedAt?: Date | null;
};

/** Render a CFPB-style dispute letter as a printable PDF buffer. */
export async function renderLetterPdf(input: PdfLetterInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
      info: {
        Title: `Fresh Start dispute — ${input.recipientName}`,
        Author: "Fresh Start",
        Subject: "Credit report dispute letter",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fontSize(9)
      .fillColor("#5a6f6a")
      .text("Fresh Start · Consumer dispute packet", { align: "left" });
    doc.moveDown(0.3);
    doc
      .fontSize(8)
      .text(
        `${input.recipientType === "cra" ? "Credit reporting company" : "Information furnisher"}: ${input.recipientName}`,
      );
    if (input.trackingNumber) {
      doc.text(
        `Certified mail tracking: ${input.trackingNumber}${
          input.mailedAt ? ` · Mailed ${input.mailedAt.toLocaleDateString("en-US")}` : ""
        }`,
      );
    }
    doc.moveDown(1.2);

    doc.fillColor("#0c2e2b").font("Times-Roman").fontSize(11);
    const lines = input.bodyText.replace(/\r\n/g, "\n").split("\n");
    for (const line of lines) {
      if (line.trim() === "") {
        doc.moveDown(0.55);
      } else {
        doc.text(line, { lineGap: 2 });
      }
    }

    doc.moveDown(1.5);
    doc
      .fontSize(8)
      .fillColor("#5a6f6a")
      .text(
        "Generated by Fresh Start. Not legal advice. Keep copies of all enclosures. Send copies, not originals.",
        { align: "left" },
      );

    doc.end();
  });
}

export function packetToPdfInput(packet: LetterPacket): PdfLetterInput {
  return {
    recipientName: packet.recipientName,
    recipientType: packet.recipientType,
    bureau: packet.bureau,
    bodyText: packet.bodyText,
    trackingNumber: packet.trackingNumber,
    mailedAt: packet.mailedAt,
  };
}
