import type { ClassifiedDisputeItem, ConsumerIdentity } from "@/lib/domain/types";

export function buildConsumerStatement(input: {
  consumer: ConsumerIdentity;
  item: ClassifiedDisputeItem;
  asOf?: Date;
}): string {
  const asOf = (input.asOf ?? new Date()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `${input.consumer.fullName}
${input.consumer.addressLine1}
${input.consumer.cityStateZip}

${asOf}

Re: Statement of dispute under the Fair Credit Reporting Act (15 U.S.C. § 1681i(b)/(c))

To Whom It May Concern:

I previously disputed the following information. After reinvestigation, the information remains on my file. I request that this statement of dispute be included in my consumer file and in any future consumer reports that include the disputed information, and that it be provided to anyone who received a report containing the disputed information in the recent past as provided by the FCRA.

Disputed information:
Creditor / furnisher: ${input.item.furnisherName ?? input.item.creditor}
Account (as shown): ${input.item.accountNumber ?? "[as shown on report]"}
Type: ${input.item.accountType}
Status reported: ${input.item.statusReported}
My statement: I continue to dispute this information as ${input.item.groundCode.replaceAll("_", " ").toLowerCase()}. ${input.item.groundRationale}

Sincerely,

${input.consumer.fullName}
`;
}

export function buildCfpbComplaintPack(input: {
  consumer: ConsumerIdentity;
  caseTitle: string;
  caseId: string;
  items: ClassifiedDisputeItem[];
  timeline: { at: string; action: string; detail?: string }[];
  asOf?: Date;
}): string {
  const asOf = (input.asOf ?? new Date()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const itemBlock = input.items
    .map(
      (item, i) =>
        `${i + 1}. ${item.creditor} (${item.groundCode}) — ${item.statusReported}; bureaus: ${item.bureaus.join(", ")}\n   ${item.groundRationale}`,
    )
    .join("\n\n");

  const timelineBlock = input.timeline
    .map((t) => `- ${t.at}: ${t.action}${t.detail ? ` — ${t.detail}` : ""}`)
    .join("\n");

  return `CFPB COMPLAINT WORKSHEET — Fresh Start export
Generated: ${asOf}
Case: ${input.caseTitle} (${input.caseId})

CONSUMER
Name: ${input.consumer.fullName}
Address: ${input.consumer.addressLine1}, ${input.consumer.cityStateZip}
Phone: ${input.consumer.phone ?? "[add phone]"}
Report/file #: ${input.consumer.reportFileNumber ?? "[if available]"}

WHAT HAPPENED (summary)
I disputed inaccurate or incomplete credit reporting. The companies involved did not adequately correct or verify the information as required under the FCRA. I am submitting this packet to support a complaint with the Consumer Financial Protection Bureau.

PRODUCT
Credit reporting or credit repair services / credit report

COMPANY TYPES INVOLVED
Credit reporting companies (Equifax / Experian / TransUnion as applicable) and information furnishers listed below.

DISPUTED ITEMS
${itemBlock || "(none listed)"}

TIMELINE
${timelineBlock || "(add dates of letters, deliveries, and responses)"}

DESIRED RESOLUTION
Delete or correct the disputed information if it cannot be verified as accurate, complete, and timely; provide written investigation results; and prevent reinsertion without lawful notice.

ATTACHMENTS TO INCLUDE WHEN FILING
1. Copies of dispute letters sent to CRAs and furnishers
2. Certified mail / tracking / return receipts
3. Annotated report excerpts
4. Supporting evidence (ID, statements, etc.)
5. Investigation results / response letters
6. This worksheet

— Generated by Fresh Start · Not legal advice · Review before filing at consumerfinance.gov —
`;
}
